const pages=['axapta','sd','mp','md','summary'];
const titles={axapta:'Аксапта',sd:'Сервис Деск',mp:'Мобильное приложение',md:'МД Аудит',summary:'Итог'};
const unlockKey='work_in_programs_unlocked_v5',watchedKey='work_in_programs_watched_v3';
const completedKey='work_in_programs_completed_v2',quizKey='work_programs_quiz_v2',attemptsKey='work_programs_quiz_attempts_v2';
const releaseKey='work_in_programs_release_20261005_clean2';
let unlocked=Number(localStorage.getItem(unlockKey)||0),watched=new Set(JSON.parse(localStorage.getItem(watchedKey)||'[]'));
const players=new Map(),playback=new Map();
function videoId(frame){return frame?.title||frame?.dataset.src||''}
function pageVideos(page){return [...page.querySelectorAll('iframe[data-src]')].map(videoId)}
function pageComplete(page){const videos=pageVideos(page);return videos.length===0||videos.every(id=>watched.has(id))}
function saveWatched(){localStorage.setItem(watchedKey,JSON.stringify([...watched]))}
function stopPlayer(frame){const player=players.get(frame);if(player)player.pause().catch(()=>{});if(frame?.getAttribute('src'))frame.removeAttribute('src');players.delete(frame);playback.delete(frame);frame?.closest('.video-embed')?.classList.remove('is-playing')}
function unloadFrames(except){document.querySelectorAll('iframe[data-src]').forEach(frame=>{if(frame!==except)stopPlayer(frame)})}
function setWatchStatus(frame,text,done=false){const embed=frame.closest('.video-embed');let status=embed?.nextElementSibling;if(!status?.classList.contains('watch-status')){status=document.createElement('p');status.className='watch-status';embed?.after(status)}status.textContent=text;status.classList.toggle('done',done)}
function openNextTopic(frame){const current=frame.closest('details.program-topic');if(!current)return;const topics=[...document.querySelectorAll('#page-axapta details.program-topic')],next=topics[topics.indexOf(current)+1];if(!next)return;current.open=false;next.open=true;setTimeout(()=>next.scrollIntoView({behavior:'smooth',block:'start'}),120)}
function markWatched(frame){const id=videoId(frame);if(!id||watched.has(id))return;watched.add(id);saveWatched();setWatchStatus(frame,'Скринкаст просмотрен полностью. Можно продолжать.',true);updateProgressLocks();openNextTopic(frame)}
function handlePlayback(frame,player,status){const state=playback.get(frame)||{furthest:0,seeking:false,lastUpdate:performance.now()};const position=Number(status.position)||0,duration=Number(status.duration)||0,now=performance.now(),naturalStep=Math.max(3,(now-state.lastUpdate)/1000+2);if(status.playbackState==='ended'){const reachedEnd=duration>0&&Math.max(state.furthest,position)>=duration-20;if(reachedEnd)markWatched(frame);else if(!state.seeking){state.seeking=true;player.seek(state.furthest).then(()=>player.play()).finally(()=>{state.seeking=false})}state.lastUpdate=now;playback.set(frame,state);return}if(status.playbackState==='playing'){if(position>state.furthest+naturalStep&&!state.seeking){state.seeking=true;player.seek(state.furthest).finally(()=>{state.seeking=false})}else if(position<=state.furthest+naturalStep){state.furthest=Math.max(state.furthest,position)}}state.lastUpdate=now;playback.set(frame,state)}
async function startVideo(button){const embed=button.closest('.video-embed'),frame=embed?.querySelector('iframe[data-src]');if(!frame)return;unloadFrames(frame);const source=new URL(frame.dataset.src);source.searchParams.set('api','1');source.searchParams.set('autoplay','1');source.searchParams.set('controls','0');source.searchParams.set('controlBar','0');frame.src=source.toString();embed.classList.add('is-playing');if(watched.has(videoId(frame))){setWatchStatus(frame,'Скринкаст просмотрен полностью. Можно продолжать.',true);return}setWatchStatus(frame,'Следующий раздел откроется после просмотра скринкаста.');const player=new window.PeerTubePlayer(frame);players.set(frame,player);playback.set(frame,{furthest:0,seeking:false,lastUpdate:performance.now()});try{await player.ready;player.addEventListener('playbackStatusUpdate',status=>handlePlayback(frame,player,status));await player.play()}catch(e){setWatchStatus(frame,'Запусти видео и посмотри его полностью, чтобы продолжить.')}}
function showWatchNotice(){let notice=document.getElementById('watch-notice');if(!notice){notice=document.createElement('div');notice.id='watch-notice';notice.className='watch-notice';notice.setAttribute('role','status');document.body.append(notice)}notice.textContent='Для перехода сначала посмотри скринкаст до конца.';notice.classList.add('show');clearTimeout(showWatchNotice.timer);showWatchNotice.timer=setTimeout(()=>notice.classList.remove('show'),3200)}
function updateProgressLocks(){const topics=[...document.querySelectorAll('#page-axapta details.program-topic')];topics.forEach((topic,index)=>{const previous=index===0?null:topics[index-1].querySelector('iframe[data-src]'),locked=Boolean(previous&&!watched.has(videoId(previous)));topic.classList.toggle('topic-locked',locked);topic.querySelector('summary')?.setAttribute('aria-disabled',String(locked));if(locked)topic.open=false});document.querySelectorAll('.page').forEach(page=>{const next=page.querySelector('.chapter-nav .next');if(!next)return;const ready=pageComplete(page);next.disabled=false;next.classList.toggle('is-locked',!ready);next.setAttribute('aria-disabled',String(!ready));next.title=ready?'':'Сначала посмотри все скринкасты этой главы до конца'});document.querySelectorAll('iframe[data-src]').forEach(frame=>{if(watched.has(videoId(frame)))setWatchStatus(frame,'Скринкаст просмотрен полностью. Можно продолжать.',true)})}
function applyLocks(){document.querySelectorAll('.module-grid [data-page]').forEach(button=>{const locked=pages.indexOf(button.dataset.page)>unlocked;button.disabled=locked;button.setAttribute('aria-disabled',String(locked));const icon=button.querySelector('i');if(icon)icon.textContent=locked?'●':'→'})}
function go(id){if(id!=='home'&&!pages.includes(id))return;if(id!=='home'&&pages.indexOf(id)>unlocked)id='home';unloadFrames();document.querySelectorAll('.page').forEach(page=>page.classList.remove('active'));document.getElementById('page-'+id)?.classList.add('active');const nav=document.getElementById('top-nav');nav.classList.toggle('hidden',id==='home');if(id!=='home'){const index=pages.indexOf(id);document.getElementById('nav-title').textContent=titles[id];document.getElementById('nav-count').textContent=`${index+1} / ${pages.length}`;document.getElementById('progress').style.width=`${((index+1)/pages.length)*100}%`}history.replaceState({},'',id==='home'?location.pathname:'#'+id);scrollTo({top:0,behavior:'instant'});if(id==='axapta'){const topics=[...document.querySelectorAll('#page-axapta details.program-topic')];const firstUnfinished=topics.find(topic=>!watched.has(videoId(topic.querySelector('iframe[data-src]'))));if(firstUnfinished&&!topics.some(topic=>topic.open))firstUnfinished.open=true}updateProgressLocks()}
function advance(id){const current=document.querySelector('.page.active');if(current&&!pageComplete(current)){showWatchNotice();current.querySelector('.watch-status:not(.done),.video-embed')?.scrollIntoView({behavior:'smooth',block:'center'});return}unlocked=Math.max(unlocked,pages.indexOf(id));localStorage.setItem(unlockKey,String(unlocked));applyLocks();go(id)}
function unlockCompletion(){sessionStorage.setItem(quizKey,'passed');const button=document.getElementById('complete');button.disabled=false;document.getElementById('completion-text').textContent='Проверка пройдена. Нажми «Завершить», чтобы сохранить результат и закрыть курс.';setTimeout(()=>document.getElementById('completion').scrollIntoView({behavior:'smooth',block:'center'}),350)}
function checkQuiz(){const fields=[...document.querySelectorAll('.quiz select')],empty=fields.some(field=>!field.value),ok=fields.every(field=>field.value===field.dataset.answer),box=document.getElementById('feedback');if(empty){fields.forEach(field=>field.style.borderColor=!field.value?'#d36a36':'');box.className='feedback show bad';box.textContent='Выбери ответ в каждой ситуации.';return}const attempt=Number(sessionStorage.getItem(attemptsKey)||0)+1;sessionStorage.setItem(attemptsKey,String(attempt));fields.forEach(field=>field.style.borderColor=field.value===field.dataset.answer?'#2d9b71':'#d45337');if(ok){box.className='feedback show good';box.textContent='Верно! Ты выбрал подходящие программы и действия. Теперь можно завершить курс.';unlockCompletion();return}if(attempt<2){box.className='feedback show bad';box.textContent='Есть неточности. Проверь маршруты в главах и попробуй ещё раз.';return}fields.forEach(field=>{field.value=field.dataset.answer;field.style.borderColor='#2d9b71';field.disabled=true});box.className='feedback show good';box.textContent='Попытки закончились. Показаны правильные ответы — изучи их перед завершением курса.';document.querySelector('.quiz .check').disabled=true;unlockCompletion()}
function completeCourse(){const box=document.getElementById('feedback'),attempts=Number(sessionStorage.getItem(attemptsKey)||0);if(sessionStorage.getItem(quizKey)!=='passed'&&attempts<2){box.className='feedback show bad';box.textContent='Сначала пройди итоговую проверку.';box.scrollIntoView({behavior:'smooth',block:'center'});return}try{localStorage.setItem(completedKey,'passed')}catch(e){}window.SCORM?.complete?.();window.SCORM?.finish?.();const button=document.getElementById('complete');button.disabled=true;button.textContent='Завершено';document.getElementById('completion-title').textContent='Курс пройден';document.getElementById('completion-text').textContent='Результат сохранён. Окно курса можно закрыть.';setTimeout(()=>{try{window.close()}catch(e){}},500)}
addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('details.program-topic').forEach(details=>details.addEventListener('toggle',()=>{if(details.open){if(details.classList.contains('topic-locked')){details.open=false;return}unloadFrames();document.querySelectorAll('details.program-topic[open]').forEach(other=>{if(other!==details)other.open=false})}else stopPlayer(details.querySelector('iframe[data-src]'))}));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.target.classList.contains('is-playing')&&entry.intersectionRatio<.15)stopPlayer(entry.target.querySelector('iframe[data-src]'))}),{threshold:[0,.15]});document.querySelectorAll('.video-embed').forEach(embed=>observer.observe(embed));const url=new URL(location.href);const newRelease=localStorage.getItem(releaseKey)!=='ready';if(newRelease||url.searchParams.get('reset')==='1'){Object.keys(localStorage).filter(key=>key.startsWith('work_in_programs_')).forEach(key=>localStorage.removeItem(key));Object.keys(sessionStorage).filter(key=>key.startsWith('work_programs_')).forEach(key=>sessionStorage.removeItem(key));localStorage.setItem(releaseKey,'ready');unlocked=0;watched=new Set();url.searchParams.delete('reset');history.replaceState({},'',url.pathname)}applyLocks();updateProgressLocks();const saved=localStorage.getItem(completedKey)==='passed';if(saved){document.getElementById('complete').disabled=true;document.getElementById('complete').textContent='Завершено';document.getElementById('completion-title').textContent='Курс пройден';document.getElementById('completion-text').textContent='Результат сохранён. Окно курса можно закрыть.'}else if(sessionStorage.getItem(quizKey)==='passed'||Number(sessionStorage.getItem(attemptsKey)||0)>=2){document.getElementById('complete').disabled=false;document.getElementById('completion-text').textContent='Проверка пройдена. Нажми «Завершить», чтобы сохранить результат и закрыть курс.'}const requested=location.hash.slice(1);go(pages.includes(requested)&&pages.indexOf(requested)<=unlocked?requested:'home')});
