const pages=['axapta','sd','mp','md','summary'];
const titles={axapta:'Аксапта',sd:'Сервис Деск',mp:'Мобильное приложение',md:'МД Аудит',summary:'Итог'};
const unlockKey='work_in_programs_unlocked_v1';
let unlocked=Number(localStorage.getItem(unlockKey)||0);
function unloadFrames(){document.querySelectorAll('iframe[data-src]').forEach(frame=>{if(frame.getAttribute('src'))frame.removeAttribute('src')})}
function loadFrames(root){root?.querySelectorAll('iframe[data-src]').forEach(frame=>{const details=frame.closest('details');if((!details||details.open)&&!frame.getAttribute('src'))frame.src=frame.dataset.src})}
function applyLocks(){document.querySelectorAll('.module-grid [data-page]').forEach(button=>{const locked=pages.indexOf(button.dataset.page)>unlocked;button.disabled=locked;button.setAttribute('aria-disabled',String(locked));const icon=button.querySelector('i');if(icon)icon.textContent=locked?'●':'→'})}
function go(id){if(id!=='home'&&!pages.includes(id))return;if(id!=='home'&&pages.indexOf(id)>unlocked)id='home';unloadFrames();document.querySelectorAll('.page').forEach(page=>page.classList.remove('active'));const activePage=document.getElementById('page-'+id);activePage?.classList.add('active');loadFrames(activePage);const nav=document.getElementById('top-nav');nav.classList.toggle('hidden',id==='home');if(id!=='home'){const index=pages.indexOf(id);document.getElementById('nav-title').textContent=titles[id];document.getElementById('nav-count').textContent=`${index+1} / ${pages.length}`;document.getElementById('progress').style.width=`${((index+1)/pages.length)*100}%`}history.replaceState({},'',id==='home'?location.pathname:'#'+id);scrollTo({top:0,behavior:'instant'})}
function advance(id){unlocked=Math.max(unlocked,pages.indexOf(id));localStorage.setItem(unlockKey,String(unlocked));applyLocks();go(id)}
function unlockCompletion(){sessionStorage.setItem('work_programs_quiz','passed');const button=document.getElementById('complete');button.disabled=false;document.getElementById('completion-text').textContent='Проверка пройдена. Нажми «Завершить», чтобы сохранить результат.';setTimeout(()=>document.getElementById('completion').scrollIntoView({behavior:'smooth',block:'center'}),350)}
function checkQuiz(){const fields=[...document.querySelectorAll('.quiz select')],empty=fields.some(field=>!field.value),ok=fields.every(field=>field.value===field.dataset.answer),box=document.getElementById('feedback');if(empty){fields.forEach(field=>field.style.borderColor=!field.value?'#d36a36':'');box.className='feedback show bad';box.textContent='Выбери ответ в каждой ситуации.';return}const attempt=Number(sessionStorage.getItem('work_programs_quiz_attempts')||0)+1;sessionStorage.setItem('work_programs_quiz_attempts',String(attempt));fields.forEach(field=>field.style.borderColor=field.value===field.dataset.answer?'#2d9b71':'#d45337');if(ok){box.className='feedback show good';box.textContent='Верно! Ты выбрал подходящие программы и действия. Теперь можно завершить курс.';unlockCompletion();return}if(attempt<2){box.className='feedback show bad';box.textContent='Есть неточности. Проверь маршруты в главах и попробуй ещё раз.';return}fields.forEach(field=>{field.value=field.dataset.answer;field.style.borderColor='#2d9b71';field.disabled=true});box.className='feedback show good';box.textContent='Попытки закончились. Показаны правильные ответы — изучи их перед завершением курса.';document.querySelector('.quiz .check').disabled=true;unlockCompletion()}
function completeCourse(){const box=document.getElementById('feedback'),attempts=Number(sessionStorage.getItem('work_programs_quiz_attempts')||0);if(sessionStorage.getItem('work_programs_quiz')!=='passed'&&attempts<2){box.className='feedback show bad';box.textContent='Сначала пройди итоговую проверку.';box.scrollIntoView({behavior:'smooth',block:'center'});return}try{localStorage.setItem('work_in_programs_completed','passed')}catch(e){}window.SCORM?.complete?.();const button=document.getElementById('complete');button.disabled=true;button.textContent='Завершено';document.getElementById('completion-title').textContent='Курс пройден';document.getElementById('completion-text').textContent='Результат сохранён. Теперь ты знаешь основные рабочие маршруты в программах ресторана.'}
addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('details.program-topic').forEach(details=>details.addEventListener('toggle',()=>{const frame=details.querySelector('iframe[data-src]');if(!frame)return;if(details.open){if(!frame.getAttribute('src'))frame.src=frame.dataset.src}else frame.removeAttribute('src')}));const url=new URL(location.href);if(url.searchParams.get('reset')==='1'){localStorage.removeItem(unlockKey);localStorage.removeItem('work_in_programs_completed');sessionStorage.removeItem('work_programs_quiz');sessionStorage.removeItem('work_programs_quiz_attempts');unlocked=0;url.searchParams.delete('reset');history.replaceState({},'',url.pathname+(url.hash||''))}applyLocks();const saved=localStorage.getItem('work_in_programs_completed')==='passed';if(saved){document.getElementById('complete').disabled=true;document.getElementById('complete').textContent='Завершено';document.getElementById('completion-title').textContent='Курс пройден';document.getElementById('completion-text').textContent='Результат сохранён. Теперь ты знаешь основные рабочие маршруты в программах ресторана.'}else if(sessionStorage.getItem('work_programs_quiz')==='passed'||Number(sessionStorage.getItem('work_programs_quiz_attempts')||0)>=2){document.getElementById('complete').disabled=false;document.getElementById('completion-text').textContent='Проверка пройдена. Нажми «Завершить», чтобы сохранить результат.'}const requested=location.hash.slice(1);go(pages.includes(requested)&&pages.indexOf(requested)<=unlocked?requested:'home')});
